name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get install -y -qq libvips

      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          PG_USER: postgres
        run: |
          bin/rails db:test:prepare
          bin/rails test:all

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Deploy to Hatchbox
        uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
