name: Deploy

on:
  workflow_run:
    workflows: Tests
    branches: main
    types: completed

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - Deploy to Hatchbox
        uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
